// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieChecker.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MovieChecker.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MovieChecker.Domain.Models.EntryRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("WatchEntryId")
                        .HasColumnType("integer")
                        .HasColumnName("watch_entry_id");

                    b.HasKey("Id")
                        .HasName("pk_entry_ratings");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_entry_ratings_user_id");

                    b.HasIndex("WatchEntryId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_entry_ratings_watch_entry_id_user_id");

                    b.ToTable("entry_ratings", (string)null);
                });

            modelBuilder.Entity("MovieChecker.Domain.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invite_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_groups_created_by_user_id");

                    b.HasIndex("InviteCode")
                        .IsUnique()
                        .HasDatabaseName("ix_groups_invite_code");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("MovieChecker.Domain.Models.GroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_group_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_group_members_user_id");

                    b.HasIndex("GroupId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_group_members_group_id_user_id");

                    b.ToTable("group_members", (string)null);
                });

            modelBuilder.Entity("MovieChecker.Domain.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Genre")
                        .HasColumnType("text")
                        .HasColumnName("genre");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("text")
                        .HasColumnName("poster_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_movies");

                    b.ToTable("movies", (string)null);
                });

            modelBuilder.Entity("MovieChecker.Domain.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<int?>("RelatedId")
                        .HasColumnType("integer")
                        .HasColumnName("related_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_notifications_user_id_created_at");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("MovieChecker.Domain.Models.PosterImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.HasKey("Id")
                        .HasName("pk_poster_images");

                    b.ToTable("poster_images", (string)null);
                });

            modelBuilder.Entity("MovieChecker.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MovieChecker.Domain.Models.WatchEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CurrentEpisode")
                        .HasColumnType("integer")
                        .HasColumnName("current_episode");

                    b.Property<int?>("CurrentSeason")
                        .HasColumnType("integer")
                        .HasColumnName("current_season");

                    b.Property<int?>("Emotion")
                        .HasColumnType("integer")
                        .HasColumnName("emotion");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer")
                        .HasColumnName("movie_id");

                    b.Property<int?>("MyRating")
                        .HasColumnType("integer")
                        .HasColumnName("my_rating");

                    b.Property<int?>("PartnerRating")
                        .HasColumnType("integer")
                        .HasColumnName("partner_rating");

                    b.Property<string>("PrivateComment")
                        .HasColumnType("text")
                        .HasColumnName("private_comment");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("TotalEpisodes")
                        .HasColumnType("integer")
                        .HasColumnName("total_episodes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("WatchedBy")
                        .HasColumnType("integer")
                        .HasColumnName("watched_by");

                    b.Property<int?>("WatchingTime")
                        .HasColumnType("integer")
                        .HasColumnName("watching_time");

                    b.HasKey("Id")
                        .HasName("pk_watch_entries");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_watch_entries_group_id");

                    b.HasIndex("MovieId")
                        .HasDatabaseName("ix_watch_entries_movie_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_watch_entries_user_id");

                    b.ToTable("watch_entries", (string)null);
                });

            modelBuilder.Entity("MovieChecker.Domain.Models.EntryRating", b =>
                {
                    b.HasOne("MovieChecker.Domain.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entry_ratings_users_user_id");

                    b.HasOne("MovieChecker.Domain.Models.WatchEntry", "WatchEntry")
                        .WithMany("Ratings")
                        .HasForeignKey("WatchEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entry_ratings_watch_entries_watch_entry_id");

                    b.Navigation("User");

                    b.Navigation("WatchEntry");
                });

            modelBuilder.Entity("MovieChecker.Domain.Models.Group", b =>
                {
                    b.HasOne("MovieChecker.Domain.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_groups_users_created_by_user_id");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("MovieChecker.Domain.Models.GroupMember", b =>
                {
                    b.HasOne("MovieChecker.Domain.Models.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_members_groups_group_id");

                    b.HasOne("MovieChecker.Domain.Models.User", "User")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_members_users_user_id");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieChecker.Domain.Models.Notification", b =>
                {
                    b.HasOne("MovieChecker.Domain.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieChecker.Domain.Models.WatchEntry", b =>
                {
                    b.HasOne("MovieChecker.Domain.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_watch_entries_groups_group_id");

                    b.HasOne("MovieChecker.Domain.Models.Movie", "Movie")
                        .WithMany("WatchEntries")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_watch_entries_movies_movie_id");

                    b.HasOne("MovieChecker.Domain.Models.User", "User")
                        .WithMany("WatchEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_watch_entries_users_user_id");

                    b.Navigation("Group");

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieChecker.Domain.Models.Group", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("MovieChecker.Domain.Models.Movie", b =>
                {
                    b.Navigation("WatchEntries");
                });

            modelBuilder.Entity("MovieChecker.Domain.Models.User", b =>
                {
                    b.Navigation("GroupMemberships");

                    b.Navigation("Notifications");

                    b.Navigation("Ratings");

                    b.Navigation("WatchEntries");
                });

            modelBuilder.Entity("MovieChecker.Domain.Models.WatchEntry", b =>
                {
                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
