namespace ContentSearch.Domain.Models.Dtos;

public record AniListContentDto(
    int AnilistId,
    string? TitleRomaji,
    string? TitleEnglish,
    string? TitleNative,
    string? Description,
    int? SeasonYear,
    string? Season,
    string? Format,
    string? Status,
    int? Episodes,
    int? Duration,
    List<string>? Genres,
    List<string>? Tags,
    string? CoverImageLarge,
    string? CoverImageMedium,
    string? CoverImageExtraLarge,
    string? BannerImage,
    int? AverageScore,
    int? MeanScore,
    int? Popularity,
    int? Favourites,
    int? StartDateYear,
    int? StartDateMonth,
    int? StartDateDay,
    int? EndDateYear,
    int? EndDateMonth,
    int? EndDateDay,
    string? Source,
    string? CountryOfOrigin,
    bool IsAdult,
    string? SiteUrl,
    DateTime CachedAt
);
