export const queryKeys = {
    watchEntries: (status?: string, groupId?: number) => ["watchEntries", status, groupId] as const,
    archivedEntries: (groupId?: number) => ["archivedEntries", groupId] as const,
    stats: (groupId?: number) => ["stats", groupId] as const,
    groups: () => ["groups"] as const,
    permissions: (groupId?: number) => ["permissions", groupId] as const,
    memberPermissions: (groupId: number, userId: string) => ["memberPermissions", groupId, userId] as const,
    inviteLinks: (groupId: number) => ["inviteLinks", groupId] as const,
    userSettings: () => ["userSettings"] as const,
    externalSearch: (query: string, language?: string) => ["externalSearch", query, language] as const,
};

export const mutationKeys = {
    createWatchEntry: () => ["createWatchEntry"] as const,
    updateWatchEntry: () => ["updateWatchEntry"] as const,
    deleteWatchEntry: () => ["deleteWatchEntry"] as const,
    restoreWatchEntry: () => ["restoreWatchEntry"] as const,
    rateEntry: () => ["rateEntry"] as const,
    createMovie: () => ["createMovie"] as const,
    updateMovie: () => ["updateMovie"] as const,
    uploadPoster: () => ["uploadPoster"] as const,
    createGroup: () => ["createGroup"] as const,
    joinGroup: () => ["joinGroup"] as const,
    leaveGroup: () => ["leaveGroup"] as const,
    kickMember: () => ["kickMember"] as const,
    transferOwnership: () => ["transferOwnership"] as const,
    updateMemberRole: () => ["updateMemberRole"] as const,
    generateOtp: () => ["generateOtp"] as const,
    updateGroupSettings: () => ["updateGroupSettings"] as const,
    checkInviteCode: () => ["checkInviteCode"] as const,
    createInviteLink: () => ["createInviteLink"] as const,
    deleteInviteLink: () => ["deleteInviteLink"] as const,
    updateMemberPermissions: () => ["updateMemberPermissions"] as const,
    provisionUser: () => ["provisionUser"] as const,
    setLanguage: () => ["setLanguage"] as const,
    updateUserSettings: () => ["updateUserSettings"] as const,
    translateResults: () => ["translateResults"] as const,
};
